using SharedCommon.Core;

namespace SharedCommon.Core.UnitTests;

public class RequestContextTests
{
    [Fact]
    public void Default_CorrelationId_IsAutoGenerated()
    {
        var ctx = new RequestContext();
        Assert.False(string.IsNullOrWhiteSpace(ctx.CorrelationId.Value));
    }

    [Fact]
    public void Default_TenantId_IsNull()
    {
        var ctx = new RequestContext();
        Assert.Null(ctx.TenantId);
    }

    [Fact]
    public void Default_UserId_IsNull()
    {
        var ctx = new RequestContext();
        Assert.Null(ctx.UserId);
    }

    [Fact]
    public void Default_Properties_IsEmpty()
    {
        var ctx = new RequestContext();
        Assert.Empty(ctx.Properties);
    }

    [Fact]
    public void CorrelationId_CanBeSet()
    {
        var ctx = new RequestContext();
        var id = CorrelationId.From("custom-id");
        ctx.CorrelationId = id;
        Assert.Equal("custom-id", ctx.CorrelationId.Value);
    }

    [Fact]
    public void TenantId_CanBeSet()
    {
        var ctx = new RequestContext { TenantId = "tenant-1" };
        Assert.Equal("tenant-1", ctx.TenantId);
    }

    [Fact]
    public void UserId_CanBeSet()
    {
        var ctx = new RequestContext { UserId = "user-42" };
        Assert.Equal("user-42", ctx.UserId);
    }

    [Fact]
    public void Properties_CanStoreFreeformValues()
    {
        var ctx = new RequestContext();
        ctx.Properties["key"] = "value";
        ctx.Properties["count"] = 99;

        Assert.Equal("value", ctx.Properties["key"]);
        Assert.Equal(99, ctx.Properties["count"]);
    }

    [Fact]
    public void Properties_IsCaseInsensitive()
    {
        var ctx = new RequestContext();
        ctx.Properties["MyKey"] = "hello";

        Assert.Equal("hello", ctx.Properties["mykey"]);
        Assert.Equal("hello", ctx.Properties["MYKEY"]);
    }

    [Fact]
    public void ImplementsIRequestContext()
    {
        IRequestContext ctx = new RequestContext();
        Assert.NotNull(ctx.CorrelationId);
        Assert.NotNull(ctx.Properties);
    }

    [Fact]
    public void TwoInstances_HaveDifferentDefaultCorrelationIds()
    {
        var a = new RequestContext();
        var b = new RequestContext();
        Assert.NotEqual(a.CorrelationId.Value, b.CorrelationId.Value);
    }
}
