global using Xunit;
global using NSubstitute;
global using SharedCommon.MultiTenancy;
global using Microsoft.AspNetCore.Http;
global using Microsoft.Extensions.Options;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.Extensions.Configuration;
